# Generated by Django 4.2.23 on 2026-08-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0015_merge_sla_and_support_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csmnotification',
            name='notification_type',
            field=models.CharField(choices=[('org_invitation', 'Organisation Invitation'), ('sla_breach', 'SLA Breach')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('pending_customer_response', 'Pending Customer Response'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='todo', max_length=30),
        ),
    ]
