# Generated by Django 4.2.23 on 2026-08-18 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_merge_project_slug_org_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('verb', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Created'), ('pending', 'Pending'), ('info', 'Updated')], default='info', max_length=16)),
                ('target_type', models.CharField(blank=True, default='', max_length=32)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='activity_project_created_idx')],
            },
        ),
    ]
